var __argemCultureInfo = {
    name: 'en-US',

    Tarih: {
        Aylar: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        Gunler: ['Sunday', 'Monday', 'Tuesday', 'Wendesday', 'Thursday', 'Friday', 'Saturday'],
        GunlerKisa: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'St'],
        Format: 'MM/dd/yyyy',
        Ayrac: '/',
        HaftaninIlkGunu: 0,
        OncekiAy: 'Previous Month',
        SonrakiAy: 'Next Month',
        OncekiYil: 'Previous Year',
        SonrakiYil: 'Next Year',
        TakvimGoster: 'Show Calendar'
    },

    DDLText: {
        WaitMessage: " Please wait... ",
        NoRecordFound: " No matching record is found ",
        YetersizKarakter: " Please enter at least {0} characters. ",
        VeriGetir: " Get data ",
        Temizle: " Clear ",
        WSTokenKeyHiddenIdYok: "Token id not set."
    },

    Tree: {
        VeriGetir: " Get data ",
        Temizle: " Clear ",
        WaitMessage: " Please wait...  ",
        WSTokenKeyHiddenIdYok: "Token id not set."
    },

    Numerik: {
        ThousandSeperator: ",",
        ThousandSeperatorKeyCode: 190,
        DecimalSeperator: "."        
    },

    ArgemButton: {
        WaitMessage: "Please Wait...",
        Save: "Are you sure you want to save?",
        Delete: "Are you sure you want to delete?",
        Confirm: "Are you sure?",
        AnimationURL: '<%=WebResource("ArgemTool.Resim.LutfenBekleyiniz.gif")%>'
    },

    ArgemGrid: {
        KayitSayisiBaslik: "Number of Records :",
        PagingIlkSayfa: "First Page",
        PagingSonSayfa: "Last Page",
        PagingSonrakiSayfa: "Next Page",
        PagingOncekiSayfa: "Previous Page",
        SayfadakiKayitSayisi: "Page Size",
        GosterilecekSayfa: "Page Number",
        Sirala: "Sort",
        KolonFiltre: "Show/Hide Coloumns",
        ExportToExcel: "Export To Excel"

    },

    Popup: {
        Kapat: "Close",
        EkraniKapla: "Maximize",
        Restore: "Restore Down",
        Yenile: "Yenile",
    },

    Menu: {
        PopUpMenuAyariYapilmamis: "To use ArgemPopUp set property on ArgemMenu",
        MenuErisimToolTipF8: "Press F8 button to enter the menu",
        MenuErisimToolTipF9: "Press F9 button to enter the menu",
        AltMenuBulunamadi: "There is no sub menu",
        WSTokenKeyHiddenIdYok: "Token id not set."
    },

    Editor: {
        WSTokenKeyHiddenIdYok: "Token id not set.",
        Yazdir: 'Print',
        BulDegistir: 'Find and replace',
        TumunuSec: 'Select all',
        Kes: 'Cut',
        Kopyala: 'Copy',
        Yapistir: 'Paste',
        GeriAl: 'Undo',
        IleriAl: 'Redo',
        ResimEkle: 'Add picture',
        DosyaEkle: 'Add Document',
        FlashEkle: 'Add Flash Document',
        MediaEkle: 'Add media file',
        LinkEkle: 'Add link',
        LinkSil: 'Remove link',
        YaziUstu: 'Yazı üstü',
        YaziAlti: 'Yazı altı',
        ParagrafEkle: 'Add paragraf',
        HREkle: 'Add horizantal line',
        BugunTarihiniEkle: 'Add date time',
        BuSaatiEkle: 'add hour',
        FontAdi: 'Font name',
        FontBoyutu: 'Font size',
        YuzerPosizyon: 'Absolute position',
        Kalin: 'Bold',
        Italik: 'Italic',
        AltiCizgili: 'Underline',
        UzeriCizgili: 'Overline',
        SolaYasla: 'Left',
        Ortala: 'Center',
        SagaYasla: 'Right',
        Genislet: 'Justify',
        NumaraListeIceriAl: 'Increase indent',
        NumaraListeDisariAl: 'Decrease indent',
        NumaraListeEkle: 'Numbering',
        SekilListeEkle: 'Bullets',
        TabloCerceveGizleGoster: 'Toogle table border',
        YaziRengi: 'Font Color',
        ZeminRengi: 'Font Background Color',
        FazlaTagTemizle: 'Remove redudant tag',
        SembolEkle: 'Add symbol',
        TabloEkle: 'Add Table',
        HarfKucult: 'Lowercase',
        HarfBuyult: 'Uppercase',
        Zoom: 'Zoom',
        Renksiz: "Transparent",
        Ozel: "Custom",
        RenkSec: "Chhose Color",
        Tamam: " OK ",
        Iptal: " Cancel ",

        Yukle: "Load",
        Kapat: "Close",

        LinkEkle: "Add Link",
        URL: "URL",
        LinkText: "Text",
        Hedef: "Target",
        TabloIptal: "Cancel",
        ResimEkle: "Add Picture",
        ResimSec: "Select Picture",
        DosyaSec: "Select File",
        DosyaUzantiBulunamadi: "File extention is not found",
        DosyaEkle: "Add Document",
        MediaEkle: "Add Media File",
        FlashEkle: "Add Flash Document",
        DizinOlustur: "Create Folder",
        DizinAd: "Folder Name",
        AnaDizinSec: "Select main folder",
        DizinAdGir: "Input name of the folder",
        DizinKaydedilemedi: "Folder couldn't save",
        TanimsizHata: "Unnown error",
        DosyaDizinSilinemedi: "Folder/File couldn't delete",
        DosyaSilmeUyari: "Do you want to delete selected file?",
        DizinSilmeUyari: "Do you want to delete selected folder?",
        DosyaDizinSil: "Folder/File Delete",
        DizinSec: "Select folder",
        Yukleniyor: "Uploding...",
        DosyaYuklendi: "File loded",
        DosyaYuklenemedi: "File couldn't load",
        Bekliyor: "Waiting",
        DosyaVarsaUzerineYaz: "If file exist overwrite?",
        YuklenebilecekMaxDosyaBoyut: "Max file size to load",
        IzinVerilenDosyaUzanti: "Allowen file extention",
        DosyaYukle: 'Upload File',
        CtrlXKullan: "Press Ctrl+X to cut",
        CtrlCKullan: "Press Ctrl+C to copy",
        CtrlVKullan: "Press Ctrl+Vto Paste",
        RangeCountBirdenBuyuk: "Select only one place",
        LinkEklemekIcinTekTagSec: "Select only one place to add link",
        HarfBuyultupKucultmekIcinTekTagSec: "Select only one place to uppercase/lowercase",
        YuklemekIcinDosyaSec: "To upload select at least one file",
        YuklemekIcinDizinSec: "To upload select folder",
        DosyaKayitURLYok: "To save file URL couldn't found",
        EnFazla3DosyaYukle: "To upload select at most 3 files at a time",
        DosyaEklenmis: "The same file is attached. You cann't add again",
        DosyaUzantisiHatali: "The selected file extension isn't allowed. You can't add this file",
        DosyaListedenCikart: "Remove the file from list",
        Genislik: "Width",
        Yukseklik: "Heiht",
        Cerceve: "Border",
        Ipucu: "Tooltip",
        Kalite: "Quality",
        Oynat: "Play",
        Surekli: "Continious",
        FlashMenu: "Flash Menu",
        Transparent: "Transparent",
        CellSpacing: "Cell Spacing",
        CellPadding: "Cell Padding",
        ZeminRengi: "Background Color",
        YatayHizalama: "Horizantal Alingment",
        DikeyHizalama: "Vertical Alingment",
        HarfGirinti: "Letter spacing",
        YukseklikGirinti: "Line height",
        Aralik: "Text indent",
        YatayHiza: ['', 'Select', 'left', 'Left', 'center', 'Center', 'right', 'Right'],
        DikeyHiza: ['', 'Select', 'top', 'Top', 'middle', 'Center', 'bottom', 'Right'],
        YatayHizaP: ['', 'Select', 'left', 'Left', 'center', 'Center', 'right', 'Right', 'justify', 'Justify'],
        ResimOzellik: "Picture Properties",
        TabloOzellik: 'Table Properties',
        TabloCerceveGosterGizle: 'Toggel border',
        TabloTdOzellik: 'Table Cell Properties',
        TabloUstSatirEkle: 'Insert Rows Above',
        TabloAltSatirEkle: 'Insert Rows Below',
        TabloSatirSil: 'Delete Rows',
        TabloSolKolonEkle: 'Insert Columns to the Left',
        TabloSagKolonEkle: 'Insert Columns to the Right',
        TabloKolonSil: 'Delete Columns',
        ParagrafOzellik: "Paragraph Properties",
        POzellik: 'Paragraph Properties',
        AOzellik: 'Link Properties',
        VTTutulanDosyalarIcinFlashEklenemez: 'Cannto load flash (swf) that all files store in database option OK',
        /*ASil: 'Remove Link',*/
        Tarihler: ['05/21/2011', '05/21/2011 15:23', '05/21/2011 15:23:23', '05/21/2011 Friday', '05/21/2011 Friday 15:23', '05/21/2011 Friday 15:23:12', 'May/21/2011', 'May/21/2011 15:23', 'May/21/2011 15:23:12', 'May/21/2011 Friday', 'May/21/2011 Friday 15:23', 'May/21/2011 Friday 15:23:12', '15:23', '15:23:12']/*,
        YukleYatayURL: '/<%=WebResource("ArgemTool.Resim.YukleYatay.gif")%>'*/
    },

    Chart: {
        WaitMessage: " Please Wait... ",
        SysError: " System error. ",
        NoChartCreat: " Chart creat error. ",
        WSTokenKeyHiddenIdYok: "Token id not set."
    }
};