var __argemCultureInfo = {
    name: "tr-TR",

    Tarih: {
        Aylar: ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"],
        Gunler: ["Pazar", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Suma", "Cumartesi"],
        GunlerKisa: ["Pt", "Sa", "Ça", "Pe", "Cu", "Ct", "Pa"],
        Format: "dd.MM.yyyy",
        Ayrac: ".",
        HaftaninIlkGunu: 1,
        OncekiAy: "Önceki Ay",
        SonrakiAy: "Sonraki Ay",
        OncekiYil: "Önceki Yıl",
        SonrakiYil: "Sonraki Yıl",
        TakvimGoster: "Takvim Göster"
    },

    DDLText: {
        WaitMessage: " Lütfen bekleyiniz ",
        NoRecordFound: " Kayıt bulunamadı ",
        YetersizKarakter: " En az {0} adet karakter giriniz. ",
        VeriGetir: " Veri Getir ",
        Temizle: " Temizle ",
        WSTokenKeyHiddenIdYok: "Token id tanımlanmamış."
    },

    Tree: {
        VeriGetir: " Veri Getir ",
        Temizle: " Temizle ",
        WaitMessage: " Lütfen bekleyiniz ",
        WSTokenKeyHiddenIdYok: "Token id tanımlanmamış."
    },

    Numerik: {
        ThousandSeperator: ".",
        ThousandSeperatorKeyCode: 188,
        DecimalSeperator: ","
    },

    ArgemButton: {
        WaitMessage: "İşleminiz gerçekleştiriliyor. Lütfen bekleyiniz...",
        Save: "Kaydetmek istediğinizden emin misiniz?",
        Delete: "Silmek istediğinizden emin misiniz?",
        Confirm: "Bu işlemi onaylamak istediğinizden emin misiniz?",
        AnimationURL: '<%=WebResource("ArgemTool.Resim.LutfenBekleyiniz.gif")%>'
    },

    ArgemGrid: {
        KayitSayisiBaslik: "Kayıt Sayısı :",
        PagingIlkSayfa: "İlk Sayfa",
        PagingSonSayfa: "Son Sayfa",
        PagingSonrakiSayfa: "Sonraki Sayfa",
        PagingOncekiSayfa: "Önceki Sayfa",
        SayfadakiKayitSayisi: "Sayfadaki Kayıt Sayısı",
        GosterilecekSayfa: "Sayfa Numarası",
        Sirala: "Sırala",
        KolonFiltre: "Gösterilecek Kolonları Belirle",
        ExportToExcel: "Excel'e Aktar"
    },

    Popup: {
        Kapat: "Kapat",
        EkraniKapla: "Ekranı Kapla",
        Restore: "Geri Yükle",
        Yenile: "Yenile",
    },

    Menu: {
        PopUpMenuAyariYapilmamis: "Menü için kullanılacak Argem PopUp sayfa açma ayarı yapılmamış",
        MenuErisimToolTipF8: "Menüye erişmek için F8 tuşunu kullanınız",
        MenuErisimToolTipF9: "Menüye erişmek için F9 tuşunu kullanınız",
        AltMenuBulunamadi: "Alt menü bulunamadı",
        WSTokenKeyHiddenIdYok: "Token id tanımlanmamış."
    },

    Editor: {
        WSTokenKeyHiddenIdYok: "Token id tanımlanmamış.",
        Yazdir: 'Yazdır',
        BulDegistir: 'Bul değiştir',
        TumunuSec: 'Tümünü Seç',
        Kes: 'Kes',
        Kopyala: 'Kopyala',
        Yapistir: 'Yapıştır',
        GeriAl: 'Geri al',
        IleriAl: 'İleri al',
        ResimEkle: 'Resim ekle',
        DosyaEkle: 'Dosya ekle',
        FlashEkle: 'Flash ekle',
        MediaEkle: 'Media ekle',
        LinkEkle: 'Link ekle',
        LinkSil: 'Link sil',
        YaziUstu: 'Yazı üstü',
        YaziAlti: 'Yazı altı',
        ParagrafEkle: 'Paragraf ekle',
        HREkle: 'HR ekle',
        BugunTarihiniEkle: 'Bu gün tarihini ekle',
        BuSaatiEkle: 'Bu saati ekle',
        FontAdi: 'Font adı',
        FontBoyutu: 'Font boyutu',
        YuzerPosizyon: 'Yüzer posizyon',
        Kalin: 'Kalın',
        Italik: 'İtalik',
        AltiCizgili: 'Altı çizgili',
        UzeriCizgili: 'Üzeri çizgili',
        SolaYasla: 'Sola yasla',
        Ortala: 'Ortala',
        SagaYasla: 'Sağa yasla',
        Genislet: 'Genişlet',
        NumaraListeIceriAl: 'Numara liste içeri al',
        NumaraListeDisariAl: 'Numara liste dışarı al',
        NumaraListeEkle: 'Numara liste ekle',
        SekilListeEkle: 'Şekil liste ekle',
        TabloCerceveGizleGoster: 'Tablo Göster/Gizle',
        YaziRengi: 'Yazı rengi',
        ZeminRengi: 'Zemin rengi',
        FazlaTagTemizle: 'Fazla tag temizle',
        SembolEkle: 'Sembol ekle',
        TabloEkle: 'Tablo ekle',
        HarfKucult: 'Harf küçült',
        HarfBuyult: 'Harf büyült',
        Zoom: 'Zoom',
        Renksiz: "Renksiz",
        Ozel: "Özel",
        RenkSec: "Renk Seç",
        Tamam: "Tamam",
        Iptal: "İptal",

        Yukle: "Yükle",
        Kapat: "Kapat",

        LinkEkle: "Link Ekle",
        URL: "URL",
        LinkText: "Text",
        Hedef: "Hedef",
        TabloIptal: "İptal",
        ResimEkle: "Resim Ekle",
        ResimSec: "Resim seçiniz",
        DosyaSec: "Dosya seçiniz",
        DosyaUzantiBulunamadi: "Dosya uzantısı bulunamadı",
        DosyaEkle: "Dosya Ekle",
        MediaEkle: "Media Ekle",
        FlashEkle: "Flash Ekle",
        DizinOlustur: "Dizin Oluştur",
        DizinAd: "Dizin Ad",
        AnaDizinSec: "Ana dizin seçiniz",
        DizinAdGir: "Dizin adı giriniz",
        DizinKaydedilemedi: "Dizin kaydedilemedi",
        TanimsizHata: "Tanımsız hata",
        DosyaDizinSilinemedi: "Dosya/Dizin silinemedi",
        DosyaSilmeUyari: "Seçili dosyayı silmek istediğinize emin misiniz?",
        DizinSilmeUyari: "Seçili dizini ve altında bulunan tüm dizin ve dosyaları silmek istediğinize emin misiniz?",
        DosyaDizinSil: "Dosya/Dizin Sil",
        DizinSec: "Dizin seçiniz",
        Yukleniyor: "Yükleniyor...",
        DosyaYuklendi: "Dosya yüklendi",
        DosyaYuklenemedi: "Dosya yüklenemedi",
        Bekliyor: "Bekliyor",
        DosyaVarsaUzerineYaz: "Dosya var ise üzerine yaz?",
        YuklenebilecekMaxDosyaBoyut: "Yüklenebilecek en fazla dosya boyutu",
        IzinVerilenDosyaUzanti: "İzin verilen dosya uzuntıları",
        DosyaYukle: "Dosya Yükle",
        CtrlXKullan: "Kesmek için Ctrl+X'i kullanınız",
        CtrlCKullan: "Kopyalamak için Ctrl+C'yi kullanınız",
        CtrlVKullan: "Yapıştırmak için Ctrl+V'yi kullanınız",
        RangeCountBirdenBuyuk: "Sadece tek bir yer seçiniz",
        LinkEklemekIcinTekTagSec: "Link eklemek için tek yer seçiniz",
        HarfBuyultupKucultmekIcinTekTagSec: "Harf büyültüp küçültmek için tek yer seçiniz",
        YuklemekIcinDosyaSec: "Yüklemek için en az 1 dosya seçmelisiniz",
        YuklemekIcinDizinSec: "Yüklemek için dizin seçmelisiniz",
        DosyaKayitURLYok: "Dosya kayıt URL bulunamadı",
        EnFazla3DosyaYukle: "Tek seferde en fazla 3 dosya yükleyebilirsiniz",
        DosyaEklenmis: "Aynı dosya eklenmiş durumda. Tekrar ekleyemezsiniz",
        DosyaUzantisiHatali: "Seçilen dosya uzantısı izin verilen dosya uzantılarından değil. Bu dosyayı ekleyemezsiniz",
        DosyaListedenCikart: "Dosyayı listeden çıkar",
        Genislik: "Genişlik",
        Yukseklik: "Yükseklik",
        Cerceve: "Çerçeve",
        Ipucu: "İpucu",
        Kalite: "Kalite",
        Oynat: "Oynat",
        Surekli: "Sürekli",
        FlashMenu: "Flash Menü",
        Transparent: "Transparent",
        CellSpacing: "Cell Spacing",
        CellPadding: "Cell Padding",
        ZeminRengi: "Zemin Rengi",
        YatayHizalama: "Yatay Hizalama",
        DikeyHizalama: "Dikey Hizalama",
        HarfGirinti: "Harf Girinti",
        YukseklikGirinti: "Yükseklik Girinti",
        Aralik: "Aralık",
        YatayHiza: ['', 'Seçiniz', 'left', 'Sol', 'center', 'Orta', 'right', 'Sağ'],
        DikeyHiza: ['', 'Seçiniz', 'top', 'Üst', 'middle', 'Orta', 'bottom', 'Alt'],
        YatayHizaP: ['', 'Seçiniz', 'left', 'Sol', 'center', 'Orta', 'right', 'Sağ', 'justify', 'Genişlet'],
        ResimOzellik: "Resim Özelliği",
        TabloOzellik: 'Tablo Özelliği',
        TabloCerceveGosterGizle: 'Tablo Çerçeve Göster/Gizle',
        TabloHucreOzellik: "Tablo Hücre Özelliği",
        ParagrafOzellik: "Paragraf Özelliği",
        TabloUstSatirEkle: 'Üste Satır Ekle',
        TabloAltSatirEkle: 'Alta Satır Ekle',
        TabloSatirSil: 'Satır Sil',
        TabloSolKolonEkle: 'Sola Kolon Ekle',
        TabloSagKolonEkle: 'Sağa Kolon Ekle',
        TabloKolonSil: 'Kolon Sil',
        AOzellik: 'Link Özelliği',
        VTTutulanDosyalarIcinFlashEklenemez:'Veri tabanında tutulan dosyalar için flash (swf) eklenemez',
        Tarihler: ['01.01.2011', '01.01.2011 15:23', '01.01.2011 15:23:23', '01.01.2011 Cuma', '01.01.2011 Cuma 15:23', '01.01.2011 Cuma 15:23:12', '01.Ocak.2011', '01.Ocak.2011 15:23', '01.Ocak.2011 15:23:12', '01.Ocak.2011 Cuma', '01.Ocak.2011 Cuma 15:23', '01.Ocak.2011 Cuma 15:23:12', '15:23', '15:23:12']/*,
        YukleYatayURL: '/<%=WebResource("ArgemTool.Resim.YukleYatay.gif")%>'*/
    },

    Chart: {
        WaitMessage: " Lütfen bekleyiniz... ",
        SysError: " Sistem hatası.",
        NoChartCreat: " Chart oluşturulamadı. ",
        WSTokenKeyHiddenIdYok: "Token id tanımlanmamış."
    }

};